### ISSUE TITLE
pylucid-boot.py: setuptools pip failed with error code 1

### ISSUE THREAD

**Issue by jedie** [jedie/PyLucid#81]
```
~$ python3 pylucid-boot.py PyLucid_env
...
Installing setuptools, pip...
  Complete output from command /home/jens/PyLucid_env_py3/bin/python3 -c "import sys, pip; sys...d\"] + sys.argv[1:]))" setuptools pip:
  Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named 'pip'
----------------------------------------
...Installing setuptools, pip...done.
Traceback (most recent call last):
  File "pylucid-boot.py", line 2682, in <module>
    main()
  File "pylucid-boot.py", line 833, in main
    symlink=options.symlink)
  File "pylucid-boot.py", line 1001, in create_environment
    install_wheel(to_install, py_executable, search_dirs)
  File "pylucid-boot.py", line 969, in install_wheel
    'PIP_NO_INDEX': '1'
  File "pylucid-boot.py", line 911, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command /home/jens/PyLucid_env_py3/bin/python3 -c "import sys, pip; sys...d\"] + sys.argv[1:]))" setuptools pip failed with error code 1

~$ python3 --version
Python 3.4.0
```

This is a known Bug, see: https://github.com/pypa/virtualenv/issues/564 and: http://bugs.python.org/issue20621

**Comment by jedie** [comment]
doesn't appear any more...
