### ISSUE TITLE
pylucid-boot.py doesn't install Click

### ISSUE THREAD

**Issue by DipSwitch** [jedie/PyLucid#82]
$ pylucid_installer ~/dev/test-pylucid/ --name=test
Traceback (most recent call last):
  File "/home/dipswitch/dev/pylucid/bin/pylucid_installer", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/home/dipswitch/dev/pylucid/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3023, in <module>
    working_set = WorkingSet._build_master()
  File "/home/dipswitch/dev/pylucid/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 614, in _build_master
    ws.require(__requires__)
  File "/home/dipswitch/dev/pylucid/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 920, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/dipswitch/dev/pylucid/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 807, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: Click

**Comment by jedie** [comment]
Please use python 3 ;)

**Comment by DipSwitch** [comment]
Maybe the website needs a update though http://www.pylucid.org/en/documentation/install-PyLucid/pylucid-boot/ ;) or remove the doc from the site so there is no redundancy to the markdown file in the repository :)

**Comment by jedie** [comment]
Yes the website is outdated. All pages are for v1 and not for the new v2 django-cms branch ;)

I will change this, if pylucid.org use the new v2 version.
